"use client";

import { useState } from "react";

import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { useAttendanceSettings, useSaveAttendanceSettings } from "@/hooks/use-attendance-integration";
import type { AttendanceIntegrationSettings as AttendanceIntegrationSettingsRow } from "@/lib/types/database";

export function AttendanceIntegrationSettings() { const query = useAttendanceSettings(); if (query.isLoading) return <LoadingState label="Loading attendance settings…" />; if (query.error || !query.data) return <ErrorState message={query.error?.message ?? "Attendance settings are unavailable."} />; return <SettingsForm key={query.data.updated_at} settings={query.data} />; }

function SettingsForm({ settings }: { settings: AttendanceIntegrationSettingsRow }) { const save = useSaveAttendanceSettings(); const [values, setValues] = useState({ workdayStart: settings.workday_start.slice(0, 5), lateGraceMinutes: settings.late_grace_minutes, templateVersion: settings.template_version, isEnabled: settings.is_enabled }); return <section className="max-w-2xl space-y-4 rounded-xl border p-5"><div><h2 className="font-semibold">CSV/XLSX integration</h2><p className="mt-1 text-sm text-muted-foreground">Adapter: {settings.adapter_key}. Timezone: {settings.timezone}. Vendor credentials never belong in browser code.</p></div><label className="grid gap-1 text-sm">Workday start<input className="rounded-lg border p-2" onChange={(event) => setValues({ ...values, workdayStart: event.target.value })} type="time" value={values.workdayStart} /></label><label className="grid gap-1 text-sm">Late grace minutes<input className="rounded-lg border p-2" max="120" min="0" onChange={(event) => setValues({ ...values, lateGraceMinutes: Number(event.target.value) })} type="number" value={values.lateGraceMinutes} /></label><label className="grid gap-1 text-sm">Template version<input className="rounded-lg border p-2" onChange={(event) => setValues({ ...values, templateVersion: event.target.value })} value={values.templateVersion} /></label><label className="flex items-center gap-2 text-sm"><input checked={values.isEnabled} onChange={(event) => setValues({ ...values, isEnabled: event.target.checked })} type="checkbox" /> Enable imports</label><button className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={save.isPending} onClick={() => save.mutate(values)} type="button">Save settings</button>{save.error ? <p className="text-sm text-destructive">{save.error.message}</p> : null}<aside className="rounded-lg bg-muted p-3 text-sm"><p className="font-medium">Future biometric vendor checklist</p><p className="mt-1 text-muted-foreground">Keep stable external IDs, preserve event semantics and idempotency, document credentials outside the browser, and test the adapter before replacing CSV/XLSX.</p></aside></section>; }
