"use client";

import { useState } from "react";

import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { useAttendanceEmployees, useResolveUnmatchedAttendanceEvent, useUnmatchedAttendanceEvents } from "@/hooks/use-attendance-integration";

export function UnmatchedAttendanceQueue() { const events = useUnmatchedAttendanceEvents({ page: 1, pageSize: 25 }); const employees = useAttendanceEmployees(); const resolve = useResolveUnmatchedAttendanceEvent(); const [selected, setSelected] = useState<Record<string, string>>({}); if (events.isLoading || employees.isLoading) return <LoadingState label="Loading unmatched attendance events…" />; if (events.error || employees.error) return <ErrorState message={(events.error ?? employees.error)?.message ?? "Unable to load attendance events."} />; return <section className="space-y-3">{(events.data?.rows ?? []).length ? events.data?.rows.map((event) => <article className="rounded-xl border p-4" key={event.id}><p className="font-medium">{event.external_employee_id}</p><p className="mt-1 text-sm text-muted-foreground">{event.attendance_date} · {event.source_event_id}</p><div className="mt-3 flex flex-wrap gap-2"><label className="sr-only" htmlFor={`employee-${event.id}`}>Employee for {event.external_employee_id}</label><select className="rounded-lg border p-2 text-sm" id={`employee-${event.id}`} onChange={(change) => setSelected((current) => ({ ...current, [event.id]: change.target.value }))} value={selected[event.id] ?? ""}><option value="">Select an employee</option>{(employees.data ?? []).map((employee) => <option key={employee.id} value={employee.id}>{employee.employee_number} — {employee.first_name} {employee.last_name}</option>)}</select><button className="rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={!selected[event.id] || resolve.isPending} onClick={() => resolve.mutate({ unmatchedEventId: event.id, employeeId: selected[event.id], externalEmployeeId: event.external_employee_id })} type="button">Map and resolve</button></div></article>) : <p className="rounded-xl border p-4 text-sm text-muted-foreground">No unmatched attendance events.</p>}{resolve.error ? <p className="text-sm text-destructive">{resolve.error.message}</p> : null}</section>; }
