"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ErrorState } from "@/components/ui/error-state";
import { FormField } from "@/components/ui/form-field";
import { LoadingState } from "@/components/ui/loading-state";
import { useDecideProfileChangeRequest, useProfileChangeDocumentUrl, useProfileChangeRequest } from "@/hooks/use-profile-change-requests";
import type { ProfileChangeRequestChange, ProfileChangeRequestDocument, ProfileChangeRequestHistory } from "@/lib/types/database";
import { profileChangeDecisionSchema } from "@/schemas/profile-change-requests";
function DocumentLink({ document }: { document: ProfileChangeRequestDocument }) { const url = useProfileChangeDocumentUrl(document.object_path); if (url.isLoading) return <span className="text-sm text-muted-foreground">Preparing {document.file_name}…</span>; if (url.error) return <span className="text-sm text-destructive">{document.file_name}: unavailable</span>; return <a className="text-sm underline" href={url.data} rel="noreferrer" target="_blank">{document.file_name} ({Math.ceil(document.size_bytes / 1024)} KB)</a>; }
function ChangeCard({ change }: { change: ProfileChangeRequestChange }) { const label = change.kind === "contact" ? change.field_key : `Qualification ${change.operation}`; return <li className="rounded-xl border p-4"><h3 className="font-medium capitalize">{label?.replace(/([A-Z])/g, " $1")}</h3><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="font-medium text-muted-foreground">Submitted snapshot</dt><dd className="mt-1 whitespace-pre-wrap rounded-lg bg-muted p-2">{JSON.stringify(change.original_value, null, 2)}</dd></div><div><dt className="font-medium text-muted-foreground">Requested change</dt><dd className="mt-1 whitespace-pre-wrap rounded-lg bg-muted p-2">{JSON.stringify(change.requested_value, null, 2)}</dd></div></dl></li>; }
function History({ entries }: { entries: ProfileChangeRequestHistory[] }) { return <ol className="space-y-2">{[...entries].sort((a, b) => a.created_at.localeCompare(b.created_at)).map((entry) => <li className="text-sm" key={entry.id}><span className="font-medium capitalize">{entry.event_type}</span> <time className="text-muted-foreground" dateTime={entry.created_at}>— {new Date(entry.created_at).toLocaleString()}</time></li>)}</ol>; }
export function AdminProfileChangeRequestDetail({ requestId }: { requestId: string }) {
  const request = useProfileChangeRequest(requestId); const decide = useDecideProfileChangeRequest(); const router = useRouter(); const [reason, setReason] = useState(""); const [error, setError] = useState<string | null>(null);
  if (request.isLoading) return <LoadingState label="Loading profile-change request…" />;
  if (request.error || !request.data) return <ErrorState message={request.error?.message ?? "Profile-change request not found."} />;
  const data = request.data as { status: "pending" | "approved" | "rejected" | "cancelled"; note: string | null; decision_reason: string | null; created_at: string; profile_change_request_changes: ProfileChangeRequestChange[]; profile_change_request_documents: ProfileChangeRequestDocument[]; profile_change_request_history: ProfileChangeRequestHistory[] };
  async function decideRequest(decision: "approved" | "rejected") { const parsed = profileChangeDecisionSchema.safeParse({ requestId, decision, reason }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Enter a valid decision."); return; } setError(null); try { await decide.mutateAsync(parsed.data); router.push("/admin/profile-change-requests"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to record this decision."); } }
  return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Review request</h2><p className="text-sm text-muted-foreground">Submitted {new Date(data.created_at).toLocaleString()}</p></div><Badge className="capitalize" variant={data.status === "approved" ? "secondary" : data.status === "rejected" ? "destructive" : "outline"}>{data.status}</Badge></div>{data.note ? <section><h3 className="font-medium">Employee note</h3><p className="mt-2 rounded-lg bg-muted p-3 text-sm">{data.note}</p></section> : null}<section><h3 className="font-medium">Requested changes</h3><ul className="mt-3 space-y-3">{data.profile_change_request_changes.map((change) => <ChangeCard change={change} key={change.id} />)}</ul></section>{data.profile_change_request_documents.length ? <section><h3 className="font-medium">Supporting documents</h3><ul className="mt-3 space-y-2">{data.profile_change_request_documents.map((document) => <li key={document.id}><DocumentLink document={document} /></li>)}</ul></section> : null}<section><h3 className="font-medium">Request history</h3><div className="mt-3 rounded-xl border p-4"><History entries={data.profile_change_request_history} /></div></section>{data.decision_reason ? <p className="rounded-lg bg-muted p-3 text-sm"><span className="font-medium">Decision reason:</span> {data.decision_reason}</p> : null}{data.status === "pending" ? <section className="space-y-3 rounded-xl border p-4"><FormField htmlFor="decision-reason" label="Rejection reason (required only when rejecting)"><textarea className="min-h-24 w-full rounded-lg border border-input bg-background px-2.5 py-2 text-sm" id="decision-reason" maxLength={2000} onChange={(event) => setReason(event.target.value)} value={reason} /></FormField>{error ? <ErrorState message={error} /> : null}<div className="flex flex-col gap-2 sm:flex-row"><Button disabled={decide.isPending} onClick={() => void decideRequest("approved")} type="button">Approve request</Button><Button disabled={decide.isPending} onClick={() => void decideRequest("rejected")} type="button" variant="destructive">Reject request</Button></div></section> : null}</section>;
}
