"use client";
import { useState } from "react";
import { useEmployeeForCurrentUser } from "@/hooks/use-personnel-records";
import { useSubmitProfileChangeRequest } from "@/hooks/use-profile-change-requests";
import { Button } from "@/components/ui/button";
import { ErrorState } from "@/components/ui/error-state";

export function ProfileChangeRequestForm() {
  const employee = useEmployeeForCurrentUser(); const submit = useSubmitProfileChangeRequest(); const [error, setError] = useState<string | null>(null);
  if (!employee.data) return <ErrorState message="Your official employee record is not available." />;
  async function onSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const values = Object.fromEntries(new FormData(event.currentTarget)); const changes = ([['personalEmail','personal_email'],['phone','phone'],['address','address'],['emergencyContactName','emergency_contact_name'],['emergencyContactPhone','emergency_contact_phone']] as const).flatMap(([field,key]) => { const next = String(values[field] ?? '').trim() || null; const current = employee.data?.[key] ?? null; return next === current ? [] : [{ kind: 'contact', field, originalValue: current, requestedValue: next }]; }); if (!changes.length) return setError("Change at least one contact field before submitting."); try { await submit.mutateAsync({ draft: { requestId: crypto.randomUUID(), note: String(values.note ?? ''), changes }, files: Array.from((event.currentTarget.elements.namedItem('documents') as HTMLInputElement).files ?? []) }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to submit the request."); } }
  return <form className="space-y-4" onSubmit={onSubmit}><p className="text-sm text-muted-foreground">Your official record stays unchanged until a System Administrator approves this request.</p><label className="block text-sm">Personal email<input className="mt-1 w-full rounded border p-2" defaultValue={employee.data.personal_email} name="personalEmail" type="email" /></label><label className="block text-sm">Phone<input className="mt-1 w-full rounded border p-2" defaultValue={employee.data.phone ?? ''} name="phone" /></label><label className="block text-sm">Address<textarea className="mt-1 w-full rounded border p-2" defaultValue={employee.data.address ?? ''} name="address" /></label><label className="block text-sm">Emergency contact name<input className="mt-1 w-full rounded border p-2" defaultValue={employee.data.emergency_contact_name ?? ''} name="emergencyContactName" /></label><label className="block text-sm">Emergency contact phone<input className="mt-1 w-full rounded border p-2" defaultValue={employee.data.emergency_contact_phone ?? ''} name="emergencyContactPhone" /></label><label className="block text-sm">Supporting documents<input accept="application/pdf,image/png,image/jpeg,image/webp" className="mt-1 block" multiple name="documents" type="file" /></label><label className="block text-sm">Note<textarea className="mt-1 w-full rounded border p-2" name="note" /></label>{error ? <ErrorState message={error} /> : null}<Button disabled={submit.isPending} type="submit">{submit.isPending ? 'Submitting…' : 'Submit request'}</Button></form>;
}
