import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import type { Employee, EmployeePromotionEligibilitySummary, PaginatedResult, PerformanceRating, PromotionCriterion, PromotionEvaluation } from "@/lib/types/database";
import { uuidSchema } from "@/schemas/common";
import { performanceRatingSchema, performanceRatingUpdateSchema, promotionCriterionSchema, promotionCriterionUpdateSchema, promotionEvaluationFiltersSchema, promotionEvaluationSchema, promotionEvaluationUpdateSchema, type PromotionEvaluationFilters } from "@/schemas/promotion-eligibility";

function throwIfError(error: { message: string } | null) { if (error) throw new Error(error.message); }
export function promotionEvaluationFilters(input: unknown = {}) { return promotionEvaluationFiltersSchema.parse(input); }

export async function listPromotionCriteria(input: { isActive?: boolean } = {}) { let query = createBrowserSupabaseClient().from("promotion_criteria").select("*, promotion_criteria_requirements(*)").order("updated_at", { ascending: false }); if (input.isActive !== undefined) query = query.eq("is_active", input.isActive); const { data, error } = await query; throwIfError(error); return (data ?? []) as Array<PromotionCriterion & { promotion_criteria_requirements: unknown[] }>; }
export async function listPromotionEvaluations(input: Partial<PromotionEvaluationFilters> = {}): Promise<PaginatedResult<PromotionEvaluation, PromotionEvaluationFilters>> { const filters = promotionEvaluationFilters(input); const from = (filters.page - 1) * filters.pageSize; let query = createBrowserSupabaseClient().from("promotion_evaluations").select("*", { count: "exact" }).order("updated_at", { ascending: false }).range(from, from + filters.pageSize - 1); if (filters.employeeId) query = query.eq("employee_id", filters.employeeId); if (filters.targetPositionId) query = query.eq("target_position_id", filters.targetPositionId); if (filters.readiness) query = query.eq("is_ready", filters.readiness === "ready"); if (filters.recommendation) query = query.eq("recommendation", filters.recommendation); const { data, error, count } = await query; throwIfError(error); return { rows: (data ?? []) as PromotionEvaluation[], count: count ?? 0, filters }; }
export async function getHrPromotionEmployee(employeeId: string) { const id = uuidSchema.parse(employeeId); const client = createBrowserSupabaseClient(); const [employee, qualifications, certifications, training, ratings, evaluations] = await Promise.all([client.from("employees").select("*").eq("id", id).maybeSingle(), client.from("qualifications").select("*").eq("employee_id", id), client.from("certifications").select("*").eq("employee_id", id), client.from("training_records").select("*").eq("employee_id", id), client.from("performance_ratings").select("*").eq("employee_id", id).order("review_period_ends_on", { ascending: false }), client.from("promotion_evaluations").select("*, promotion_evaluation_evidence(*)").eq("employee_id", id).order("updated_at", { ascending: false })]); [employee, qualifications, certifications, training, ratings, evaluations].forEach((result) => throwIfError(result.error)); if (!employee.data) return null; return { employee: employee.data as Employee, qualifications: qualifications.data ?? [], certifications: certifications.data ?? [], training: training.data ?? [], ratings: (ratings.data ?? []) as PerformanceRating[], evaluations: evaluations.data ?? [] }; }
export async function getMyPromotionEligibility() { const { data, error } = await createBrowserSupabaseClient().from("employee_promotion_eligibility_summaries").select("*").order("calculated_at", { ascending: false }).limit(1).maybeSingle(); throwIfError(error); return data as EmployeePromotionEligibilitySummary | null; }
function criterionPayload(input: unknown) { const value = promotionCriterionSchema.parse(input); return { target_position_id: value.targetPositionId, target_minimum_years: value.minimumYearsOfService, target_minimum_rating: value.minimumPerformanceRating, target_requirements: value.requirements }; }
function ratingPayload(input: unknown) { const value = performanceRatingSchema.parse(input); return { target_employee_id: value.employeeId, target_rating: value.rating, target_starts_on: value.reviewPeriodStartsOn, target_ends_on: value.reviewPeriodEndsOn, target_notes: value.notes }; }
function evaluationPayload(input: unknown) { const value = promotionEvaluationSchema.parse(input); return { target_employee_id: value.employeeId, target_position_id: value.targetPositionId, target_criterion_id: value.criterionId, target_evaluated_on: value.evaluatedOn, target_recommendation: value.recommendation, target_notes: value.notes, target_evidence: value.evidence.map(({ requirementId, qualificationId, certificationId, trainingRecordId }) => ({ requirementId, qualificationId, certificationId, trainingRecordId })) }; }
export async function createPromotionCriterion(input: unknown) { const { data, error } = await createBrowserSupabaseClient().rpc("create_promotion_criterion", criterionPayload(input)); throwIfError(error); return data as string; }
export async function updatePromotionCriterion(input: unknown) { const value = promotionCriterionUpdateSchema.parse(input); const { error } = await createBrowserSupabaseClient().rpc("update_promotion_criterion", { target_criterion_id: value.id, expected_updated_at: value.expectedUpdatedAt, target_position_id: value.targetPositionId, target_minimum_years: value.minimumYearsOfService, target_minimum_rating: value.minimumPerformanceRating, target_is_active: value.isActive, target_requirements: value.requirements }); throwIfError(error); }
export async function createPerformanceRating(input: unknown) { const { data, error } = await createBrowserSupabaseClient().rpc("create_performance_rating", ratingPayload(input)); throwIfError(error); return data as string; }
export async function updatePerformanceRating(input: unknown) { const value = performanceRatingUpdateSchema.parse(input); const { error } = await createBrowserSupabaseClient().rpc("update_performance_rating", { target_rating_id: value.id, expected_updated_at: value.expectedUpdatedAt, target_rating: value.rating, target_starts_on: value.reviewPeriodStartsOn, target_ends_on: value.reviewPeriodEndsOn, target_notes: value.notes }); throwIfError(error); }
export async function createPromotionEvaluation(input: unknown) { const { data, error } = await createBrowserSupabaseClient().rpc("create_promotion_evaluation", evaluationPayload(input)); throwIfError(error); return data as string; }
export async function updatePromotionEvaluation(input: unknown) { const value = promotionEvaluationUpdateSchema.parse(input); const { error } = await createBrowserSupabaseClient().rpc("update_promotion_evaluation", { target_evaluation_id: value.id, expected_updated_at: value.expectedUpdatedAt, target_evaluated_on: value.evaluatedOn, target_recommendation: value.recommendation, target_notes: value.notes, target_evidence: value.evidence }); throwIfError(error); }
