"use client";
import { FormEvent, useState } from "react";
import { ErrorState } from "@/components/ui/error-state";
import { Button } from "@/components/ui/button";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { useCreatePromotionCriterion } from "@/hooks/use-promotion-eligibility";
import { promotionCriterionSchema } from "@/schemas/promotion-eligibility";
export function PromotionCriteriaManager() { const create = useCreatePromotionCriterion(); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const form = Object.fromEntries(new FormData(event.currentTarget)); const parsed = promotionCriterionSchema.safeParse({ targetPositionId: form.targetPositionId, minimumYearsOfService: form.minimumYearsOfService, minimumPerformanceRating: form.minimumPerformanceRating, requirements: form.requiredName ? [{ recordKind: form.recordKind, requiredName: form.requiredName, label: form.label || form.requiredName, isMandatory: true }] : [] }); if (!parsed.success) return setError(parsed.error.issues[0]?.message ?? "Check the criteria."); try { await create.mutateAsync(parsed.data); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save criteria."); } } return <form className="grid gap-4 rounded-xl border p-5 sm:grid-cols-2" noValidate onSubmit={submit}><FormField htmlFor="target-position" label="Target position ID"><Input id="target-position" name="targetPositionId" required type="number" /></FormField><FormField htmlFor="minimum-years" label="Minimum years of service"><Input id="minimum-years" name="minimumYearsOfService" min="0" required type="number" /></FormField><FormField htmlFor="minimum-rating" label="Minimum performance rating (optional)"><Input id="minimum-rating" max="5" min="1" name="minimumPerformanceRating" type="number" /></FormField><FormField htmlFor="record-kind" label="Record kind"><select className="h-11 w-full rounded-lg border bg-background px-3" id="record-kind" name="recordKind"><option value="certification">Certification</option><option value="qualification">Qualification</option><option value="training">Training</option></select></FormField><FormField htmlFor="required-name" label="Required record name"><Input id="required-name" name="requiredName" /></FormField><FormField htmlFor="label" label="Employee-facing requirement label"><Input id="label" name="label" /></FormField>{error ? <div className="sm:col-span-2"><ErrorState message={error} /></div> : null}<div className="sm:col-span-2"><Button disabled={create.isPending} type="submit">{create.isPending ? "Saving…" : "Save criteria"}</Button></div></form>; }
