"use client";
import { type FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { ErrorState } from "@/components/ui/error-state";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { LoadingState } from "@/components/ui/loading-state";
import { useActiveLeaveTypes, useCreateLeaveType, useUpdateLeaveType } from "@/hooks/use-leave-management";
export function LeaveTypeSummary({name,requiresAttachment}:{name:string;requiresAttachment:boolean}){return <span>{name}{requiresAttachment?<span className="ml-2 text-xs text-muted-foreground">Evidence required</span>:null}</span>}
export function LeaveTypeManager(){const types=useActiveLeaveTypes();const create=useCreateLeaveType();const update=useUpdateLeaveType();const[error,setError]=useState<string|null>(null);if(types.isLoading)return <LoadingState label="Loading leave types…"/>;if(types.error)return <ErrorState message={types.error.message}/>;async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);const data=new FormData(event.currentTarget);try{await create.mutateAsync({name:String(data.get("name")),description:String(data.get("description")),requiresAttachment:data.get("requiresAttachment")==="on"});event.currentTarget.reset()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to create leave type.")}}return <section className="space-y-4 rounded-xl border p-4"><h2 className="text-lg font-semibold">Leave types</h2><form className="grid gap-3 sm:grid-cols-3" onSubmit={submit}><FormField htmlFor="type-name" label="Name"><Input required id="type-name" name="name"/></FormField><FormField htmlFor="type-description" label="Description"><Input id="type-description" name="description"/></FormField><label className="flex min-h-11 items-end gap-2 text-sm"><input name="requiresAttachment" type="checkbox"/>Evidence required</label><Button className="sm:col-span-3 sm:w-fit" disabled={create.isPending} type="submit">Add leave type</Button></form>{error?<ErrorState message={error}/>:null}<ul className="space-y-2">{types.data?.map(type=><li className="rounded-lg bg-muted px-3 py-2 text-sm" key={type.id}><div className="flex items-center justify-between gap-3"><LeaveTypeSummary name={type.name} requiresAttachment={type.requires_attachment}/><Button disabled={update.isPending} onClick={()=>update.mutate({id:type.id,name:type.name,description:type.description??undefined,requiresAttachment:type.requires_attachment,isActive:!type.is_active})} variant="outline">{type.is_active?"Deactivate type":"Activate type"}</Button></div><details className="mt-2"><summary className="cursor-pointer underline">Edit type</summary><form className="mt-2 grid gap-2 sm:grid-cols-3" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);update.mutate({id:type.id,name:String(data.get("name")),description:String(data.get("description")),requiresAttachment:data.get("requiresAttachment")==="on",isActive:type.is_active})}}><Input aria-label={`Name for ${type.name}`} defaultValue={type.name} name="name" required/><Input aria-label={`Description for ${type.name}`} defaultValue={type.description??""} name="description"/><label className="flex gap-2"><input defaultChecked={type.requires_attachment} name="requiresAttachment" type="checkbox"/>Evidence required</label><Button className="sm:w-fit" type="submit" variant="secondary">Save changes</Button></form></details></li>)}</ul></section>}
