create table public.unit_stations (
  id bigint generated by default as identity primary key,
  name text not null unique check (name = btrim(name) and length(name) between 1 and 160),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.unit_stations (name)
select distinct unit_station from public.employees where unit_station is not null and btrim(unit_station) <> ''
on conflict (name) do nothing;

alter table public.unit_stations enable row level security;
grant select on public.unit_stations to authenticated;
create policy unit_stations_select_authenticated on public.unit_stations for select to authenticated using (is_active);
